from flask.ext.babel import lazy_gettext
from forms import *

PUBTYPE2TEXT = {
    'ArticleJournal': lazy_gettext('Article in Journal'),
    'ArticleNewspaper': lazy_gettext('Article in Newspaper'),
    'AudioBook': lazy_gettext('Audio Book'),
    'AudioVideoDocument': lazy_gettext('Audio or Video Document'),
    'Chapter': lazy_gettext('Chapter in...'),
    'ChapterInLegalCommentary': lazy_gettext('Chapter in a Legal Commentary'),
    'ChapterInMonograph': lazy_gettext('Chapter in a Monograph'),
    'Collection': lazy_gettext('Collection'),
    'Conference': lazy_gettext('Conference'),
    'Edition': lazy_gettext('Edition'),
    'InternetDocument': lazy_gettext('Internet Document'),
    'Journal': lazy_gettext('Journal'),
    'Lecture': lazy_gettext('Lecture'),
    'LegalCommentary': lazy_gettext('Legal Commentary'),
    'Monograph': lazy_gettext('Monograph'),
    'MultivolumeWork': lazy_gettext('MultivolumeWork'),
    'Newspaper': lazy_gettext('Newspaper'),
    'Other': lazy_gettext('Other'),
    'Patent': lazy_gettext('Patent'),
    'PressRelease': lazy_gettext('Press Release'),
    'RadioTVProgram': lazy_gettext('Radio or TV Program'),
    'Report': lazy_gettext('Report'),
    'ResearchData': lazy_gettext('Research Data'),
    'Series': lazy_gettext('Series'),
    'Software': lazy_gettext('Software'),
    'SpecialIssue': lazy_gettext('Special Issue'),
    'Standard': lazy_gettext('Standard'),
    'Thesis': lazy_gettext('Thesis'),
}

SUBTYPE2TEXT = {
    'lexicon_article': lazy_gettext('Article in Lexicon'),
    'abstract': lazy_gettext('Abstract'),
    'afterword': lazy_gettext('Afterword'),
    'bachelor_thesis': lazy_gettext('Bachelor Thesis'),
    'diploma_thesis': lazy_gettext('Diploma Thesis'),
    'dissertation': lazy_gettext('Dissertation'),
    'dramatic_work': lazy_gettext('Dramatic Work'),
    'expert_opinion': lazy_gettext('Expert Opinion'),
    'festschrift': lazy_gettext('Festschrift'),
    'first_state_examination': lazy_gettext('1st State Examination'),
    'habilitation': lazy_gettext('Habilitation'),
    'image_database': lazy_gettext('Image Database'),
    'interview': lazy_gettext('Interview'),
    'introduction': lazy_gettext('Foreword'),
    'lecture_notes': lazy_gettext('Lecture Notes'),
    'magisterarbeit': lazy_gettext('Magisterarbeit'),
    'masters_thesis': lazy_gettext("Master's Thesis"),
    'meeting_abstract': lazy_gettext('Meeting Abstract'),
    'notated_music': lazy_gettext('Notated Music'),
    'poster': lazy_gettext('Poster'),
    'poster_abstract': lazy_gettext('Poster Abstract'),
    'report': lazy_gettext('Report'),
    'review': lazy_gettext('Review'),
    'second_state_examination': lazy_gettext('2nd State Examination'),
    'sermon': lazy_gettext('Sermon'),
}

PUBTYPE2FORM = {
    'ArticleJournal': ArticleJournalForm,
    'MultivolumeWork': MultivolumeWorkForm,
    'Monograph': MonographForm,
    'Patent': PatentForm,
    'Chapter': ChapterForm,
    'ChapterInLegalCommentary': ChapterInLegalCommentaryForm,
    'Conference': ConferenceForm,
    'Collection': CollectionForm,
    'Edition': EditionForm,
    'Other': OtherForm,
    'Thesis': ThesisForm,
    'ArticleNewspaper': ArticleNewspaperForm,
    'AudioVideoDocument': AudioVideoDocumentForm,
    'InternetDocument': InternetDocumentForm,
    'Journal': JournalForm,
    'Lecture': LectureForm,
    'LegalCommentary': LegalCommentaryForm,
    'Newspaper': NewspaperForm,
    'PressRelease': PressReleaseForm,
    'RadioTVProgram': RadioTVProgramForm,
    'Series': SeriesForm,
    'Software': SoftwareForm,
    'SpecialIssue': SpecialIssueForm,
    'Standard': StandardForm,
    'Report': ReportForm,
    'ResearchData': ResearchDataForm,
}

PUBTYPE2USERFORM = {
    'ArticleJournal': ArticleJournalUserForm,
    'Monograph': MonographUserForm,
    'Chapter': ChapterUserForm,
    'Collection': CollectionUserForm,
    'Report': ReportUserForm,
    'ResearchData': ResearchDataUserForm,
}

ROLE_MAP = {
    'abr': lazy_gettext('Abridger'),
    'act': lazy_gettext('Actor'),
    'aut': lazy_gettext('Author'),
    'aft': lazy_gettext('Author of Afterword'),
    'arr': lazy_gettext('Arranger'),
    'aui': lazy_gettext('Author of Introduction'),
    'brd': lazy_gettext('Broadcaster'),
    'chr': lazy_gettext('Choreographer'),
    'cmp': lazy_gettext('Composer'),
    'ctb': lazy_gettext('Contributor'),
    'cst': lazy_gettext('Costume Designer'),
    'cwt': lazy_gettext('Commentator for written text'),
    'dgg': lazy_gettext('Degree Granting Institution'),
    'drt': lazy_gettext('Director'),
    'edt': lazy_gettext('Editor'),
    'elg': lazy_gettext('Electrician'),
    'fmk': lazy_gettext('Filmmaker'),
    'hnr': lazy_gettext('Honoree'),
    'his': lazy_gettext('Host institution'),
    'ill': lazy_gettext('Illustrator'),
    'itr': lazy_gettext('Instrumentalist'),
    'ive': lazy_gettext('Interviewee'),
    'ivr': lazy_gettext('Interviewer'),
    'inv': lazy_gettext('Inventor'),
    'mod': lazy_gettext('Moderator'),
    'mus': lazy_gettext('Musician'),
    'org': lazy_gettext('Originator'),
    'orm': lazy_gettext('Organizer'),
    'pdr': lazy_gettext('Project Director'),
    'pht': lazy_gettext('Photographer'),
    'pmn': lazy_gettext('Production Manager'),
    'pro': lazy_gettext('Producer'),
    'prg': lazy_gettext('Programmer'),
    'pta': lazy_gettext('Patent applicant'),
    'red': lazy_gettext('Redaktor'),
    'std': lazy_gettext('Set Designer'),
    'sng': lazy_gettext('Singer'),
    'spk': lazy_gettext('Speaker'),
    'stl': lazy_gettext('Storyteller'),
    'trl': lazy_gettext('Translator'),
    'tcd': lazy_gettext('Technical Director'),
    'ths': lazy_gettext('Thesis Advisor'),
}


# see: http://www.loc.gov/marc/languages/
LANGUAGE_MAP = {
    'eng': lazy_gettext('English'),
    'ger': lazy_gettext('German'),
    'fre': lazy_gettext('French'),
    'rus': lazy_gettext('Russian'),
    'spa': lazy_gettext('Spanish'),
    'ita': lazy_gettext('Italian'),
    'jpn': lazy_gettext('Japanese'),
    'lat': lazy_gettext('Latin'),
    'zhn': lazy_gettext('Chinese'),
    'dut': lazy_gettext('Dutch'),
    'tur': lazy_gettext('Turkish'),
    'por': lazy_gettext('Portuguese'),
    'pol': lazy_gettext('Polish'),
    'gre': lazy_gettext('Greek'),
    'srp': lazy_gettext('Serbian'),
    'cat': lazy_gettext('Catalan'),
    'dan': lazy_gettext('Danish'),
    'cze': lazy_gettext('Czech'),
    'kor': lazy_gettext('Korean'),
    'ara': lazy_gettext('Arabic'),
    'hun': lazy_gettext('Hungarian'),
    'swe': lazy_gettext('Swedish'),
    'ukr': lazy_gettext('Ukranian'),
    'heb': lazy_gettext('Hebrew'),
    'hrv': lazy_gettext('Croatian'),
    'slo': lazy_gettext('Slovak'),
    'nor': lazy_gettext('Norwegian'),
    'rum': lazy_gettext('Romanian'),
    'fin': lazy_gettext('Finnish'),
    'geo': lazy_gettext('Georgian'),
    'bul': lazy_gettext('Bulgarian'),
    'grc': lazy_gettext('Ancient Greek'),
    'ind': lazy_gettext('Indonesian Language'),
    'gmh': lazy_gettext('Middle High German'),
    'mon': lazy_gettext('Mongolian Language'),
    'peo': lazy_gettext('Persian'),
    'alb': lazy_gettext('Albanian'),
    'bos': lazy_gettext('Bosnian'),
    'lit': lazy_gettext('Lithuanian'),
    'slv': lazy_gettext('Slovenian'),
    'baq': lazy_gettext('Basque'),
    'gag': lazy_gettext('Galician'),
}

FREQUENCY_MAP = {
    'completely_irregular': lazy_gettext('Completely Irregular'),
    'annual': lazy_gettext('Annual'),
    'quarterly': lazy_gettext('Quarterly'),
    'semiannual': lazy_gettext('Semiannual'),
    'monthly': lazy_gettext('Monthly'),
    'bimonthly': lazy_gettext('Bimonthly'),
    'three_times_a_year': lazy_gettext('Three Times a Year'),
    'semimonthly': lazy_gettext('Semimonthly'),
    'biennial': lazy_gettext('Biannial'),
    'fifteen_issues_a_year': lazy_gettext('Fifteen Issues a Year'),
    'continuously_updated': lazy_gettext('Continuously Updated'),
    'daily': lazy_gettext('Daily'),
    'semiweekly': lazy_gettext('Semiweekly'),
    'three_times_a_week': lazy_gettext('Three Times a Week'),
    'weekly': lazy_gettext('Weekly'),
    'biweekly': lazy_gettext('Biweekly'),
    'three_times_a_month': lazy_gettext('Three Times a Month'),
    'triennial': lazy_gettext('Triennial'),
}

URL_TYPE_MAP = {
    'hp': lazy_gettext('Homepage'),
    'rg': lazy_gettext('ResearchGate'),
    'ri': lazy_gettext('ResearcherID'),
    'an': lazy_gettext('AcademiaNet'),
    'ae': lazy_gettext('Academia.edu'),
    'wp': lazy_gettext('Wikipedia'),
    'xi': lazy_gettext('Xing'),
    'li': lazy_gettext('LinkedIn'),
    'bl': lazy_gettext('Blog'),
    'fb': lazy_gettext('Facebook'),
    'tw': lazy_gettext('Twitter'),
    'ic': lazy_gettext('identi.ca'),
    'zt': lazy_gettext('Zotero'),
    'md': lazy_gettext('Mendeley'),
    'mi': lazy_gettext('Other'),
}

LICENSE_MAP = {
    'cc_zero': lazy_gettext('Creative Commons Zero - Public Domain'),
    'cc_by': lazy_gettext('Creative Commons Attribution'),
    'cc_by_sa': lazy_gettext('Creative Commons Attribution Share Alike'),
    'cc_by_nd': lazy_gettext('Creative Commons Attribution No Derivatives')
}

PERS_STATUS_MAP = {
    'alumnus': lazy_gettext('Alumnus'),
    'assistant_lecturer': lazy_gettext('Assistant Lecturer'),
    'callcenter': lazy_gettext('Callcenter'),
    'ranking': lazy_gettext('Relevant for Ranking'),
    'external': lazy_gettext('External Staff'),
    'manually_added': lazy_gettext('Manually added'),
    'official': lazy_gettext('Official'),
    'official_ns': lazy_gettext('Official, Non-Scientific'),
    'research_school': lazy_gettext('Doctoral Candidate'),
    'principal_investigator': lazy_gettext('Principal Investigator'),
    'professor': lazy_gettext('Professor'),
    'emeritus': lazy_gettext('Emeritus'),
    'teaching_assistant': lazy_gettext('Teaching Assistant'),
    'tech_admin': lazy_gettext('Technical and Administrative Staff'),
}

LANGUAGES = {
    'de': 'German',
    'de_DE': 'German',
    'en': 'English',
    'en_GB': 'English',
    'en_US': 'English'
}

PUB_STATUS = {
    'published': lazy_gettext('Published'),
    'unpublished': lazy_gettext('Unpublished'),
    'granted': lazy_gettext('Granted')
}

EDT_STATUS = {
    'new': lazy_gettext('New'),
    'in_process': lazy_gettext('Editing'),
    'processed': lazy_gettext('Edited'),
    'final_editing': lazy_gettext('Final Editing'),
    'finalized': lazy_gettext('Finalized'),
    'imported': lazy_gettext('Imported'),
    'deleted': lazy_gettext('Deleted'),
}
